name: Filmes

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Clear Docker credentials
      run: |
        docker logout ghcr.io
        rm -rf ~/.docker/config.json

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.PACKAGES_USER}}
        password: ${{ secrets.PACKAGES_TOKEN}}

    - run: |
        docker build -t ghcr.io/testefilmes/filmes-favoritos/filmes:latest -f Dockerfile .
        docker tag ghcr.io/testefilmes/filmes-favoritos/filmes:latest ghcr.io/testefilmes/filmes-favoritos/filmes:${{ github.sha }}

    - run: |
        docker push ghcr.io/testefilmes/filmes-favoritos/filmes:latest
        docker push ghcr.io/testefilmes/filmes-favoritos/filmes:${{ github.sha }}
